swagger: "2.0"
info:
  description: "Dybov's and Lavrov's blse lab"
  title: "Rubbable api"
  version: "2.0.0"


host: "localhost:8000"
basePath: "/api"


schemes:
  - "http"
paths:

  /reports/:
    get:
      description: "Get reports list"
      produces:
        - "application/json"

      responses:
        "200":
          description: "ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ReportDto"

  /teams/:
    get:
      description: "Get teams list"
      produces:
        - "application/json"

      responses:
        "200":
          description: "ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TeamDto"

  /tournaments/stats/:
    get:
      description: "Get tournaments stats"
      produces:
        - "application/json"

      responses:
        "200":
          description: "ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TournamentStatsDto"

  /win-probability/:
    get:
      security:
        - basicAuth: [ ]
      description: "Get team by id"
      produces:
        - "application/json"
      parameters:
        - name: team1Id
          in: query
          type: integer
          required: true

        - name: team2Id
          in: query
          type: integer
          required: true

      responses:
        "200":
          description: "Probability of win of 1st team"
          schema:
            $ref: "#/definitions/WinProbabilityDto"
        "400":
          description: "Bad request"

  /win-rate/:
    get:
      security:
        - basicAuth: [ ]
      description: "Get team by id"
      produces:
        - "application/json"
      parameters:
        - name: teamId
          in: query
          type: integer
          required: true

      responses:
        "200":
          description: "Team win ratio"
          schema:
            $ref: "#/definitions/WinRatioDto"
        "400":
          description: "Bad request"


definitions:


  TeamDto:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"

  ReportDto:
    type: "object"
    properties:
      id:
        type: "integer"
      created:
        type: "string"

  TournamentStatsDto:
    type: "object"
    properties:
      id:
        type: "integer"
      teamsIds:
        type: "array"
        items:
            type: "integer"
      totalMatches:
        type: "integer"
      totalGames:
        type: "integer"

  WinProbabilityDto:
    type: "object"
    properties:
      gameProbability:
        type: "number"
      matchProbability:
        type: "number"

  WinRatioDto:
    type: "object"
    properties:
      gameWinRatio:
        type: "number"
      matchWinRatio:
        type: "number"